models/Module.php
<?php

namespace callmez\wechat\models;

use callmez\wechat\assets\WechatAsset;
use Yii;
use yii\caching\Cache;
use yii\db\ActiveRecord;
use yii\caching\TagDependency;
use yii\base\InvalidCallException;
use yii\base\NotSupportedException;
use yii\base\InvalidParamException;
use yii\behaviors\TimestampBehavior;
use Symfony\Component\Yaml\Yaml;
use callmez\wechat\helpers\ModuleHelper;
use callmez\wechat\Module as WechatModule;

/**
 * 微信扩展模块类
 * @package callmez\wechat\models
 */
class Module extends ActiveRecord
{
    /**
     * 模块数据缓存
     */
    const CACHE_MODULES_DATA = 'cache_wechat_model_moduels_data';
    /**
     * 模块数据缓存依赖标签
     */
    const CACHE_MODULES_DATA_DEPENDENCY_TAG = 'cache_wechat_model_moduels_data_tag';
    /**
     * 核心模块
     */
    const TYPE_CORE = 'core';
    /**
     * 微信扩展模块
     */
    const TYPE_ADDON = 'addon';
    /**
     * 迁移安装
     */
    const MIGRATION_INSTALL = 'install';
    /**
     * 迁移卸载
     */
    const MIGRATION_UNINSTALL = 'uninstall';
    /**
     * 迁移升级
     */
    const MIGRATION_UPGRADE = 'upgrade';
    /**
     * @var array
     */
    public static $types = [
        self::TYPE_CORE => '核心模块',
        self::TYPE_ADDON => '扩展模块',
    ];

    public function behaviors()
    {
        return [
            'timestamp' => TimestampBehavior::className()
        ];
    }

    /**
     * 禁用事务(便于执行migration)
     * @return array
     */
    final public function transactions()
    {
        return [];
    }

    /**
     * 加入安装和升级migration操作, 使用事务(self::transactions()禁止默认事务)来控制数据一致性
     * 并更新数据缓存
     * @inheritdoc
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        $transaction = static::getDb()->beginTransaction();
        try {

            if ($this->getIsNewRecord()) {
                $migrationType = self::MIGRATION_INSTALL;
                $result = $this->insert($runValidation, $attributeNames);
            } else {
                $migrationType = self::MIGRATION_UPGRADE;
                $result = $this->update($runValidation, $attributeNames) !== false;
            }
            if ($result !== false && $this->migration) {
                $result = $this->migration($migrationType);
            }

            if ($result === false) {
                $transaction->rollBack();
            } else {
                $transaction->commit();

                static::updateCache();
            }
            return $result;
        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }
    }

    /**
     * 加入卸载migration操作, 使用事务(self::transactions()禁止默认事务)来控制数据一致性
     * 并更新数据缓存
     * @inheritdoc
     */
    public function delete()
    {
        $transaction = static::getDb()->beginTransaction();
        try {
            $result = $this->deleteInternal();

            if ($result !== false && $this->migration) { // 有迁移执行迁移脚本
                $result = $this->migration(self::MIGRATION_UNINSTALL);
            }

            if ($result === false) {
                $transaction->rollBack();
            } else {
                $transaction->commit();

                static::updateCache();
            }
            return $result;
        } catch (\Exception $e) {
            $transaction->rollBack();
            throw $e;
        }
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%wechat_module}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'type', 'name', 'category', 'version'], 'required'],

            [['id'], 'string', 'max' => 20],
            [['name', 'author'], 'string', 'max' => 50],
            [['version'], 'string', 'max' => 10],
            [['ability'], 'string', 'max' => 100],
            [['site'], 'string', 'max' => 255],

            [['id'], 'match', 'pattern' => '/^[\w]+$/', 'message' => '模块唯一ID标识只能包含英文字母,数字和_符号'], // 模块ID哟福
            [['id'], 'unique', 'message' => '模块唯一ID标识已经被使用或者该模块已经安装.'],
            [['admin', 'migration', 'reply_rule'], 'boolean'],

            [['type'], 'checkType', 'skipOnEmpty' => false],
            [['category'], 'in', 'range' => array_keys(Yii::$app->getModule('wechat')->getCategories()), 'skipOnEmpty' => false],

            [['description'], 'string'],
            [['description'], 'default', 'value' => ''],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => '名称',
            'type' => '类型',
            'version' => '版本',
            'ability' => '功能简述',
            'description' => '详细描述',
            'author' => '作者',
            'site' => '模块详情地址',
            'admin' => '是否有后台界面',
            'migration' => '是否有迁移数据',
            'category' => '模块所属分类',
            'created_at' => '安装时间',
            'updated_at' => '升级时间'
        ];
    }

    /**
     * 更新列表数据缓存
     * @see callmez\wechat\Module::addonModules()
     * @param $cacheKey
     */
    public static function updateCache($cacheKey = self::CACHE_MODULES_DATA_DEPENDENCY_TAG)
    {
        $cache = Yii::$app->get(static::getDb()->queryCache, false);
        if ($cache instanceof Cache) {
            TagDependency::invalidate($cache, $cacheKey);
        }
    }

    /**
     * 执行模块迁移(安装,升级,卸载)脚本
     * @param $type
     * @return bool
     */
    protected function migration($type)
    {
        $class = ModuleHelper::getBaseNamespace($this) . '\migrations\WechatMigration';
        if (!class_exists($class)) {
            // 卸载如果迁移文件不存在也直接返回迁移成功(防止卸载失败)
            if ($type == self::MIGRATION_UNINSTALL) {
                return true;
            }
            $this->addError('migration', '模块迁移文件不存在');
            return false;
        }
        $migration = Yii::createObject([
            'class' => $class,
            'module' => $this
        ]);
        switch ($type) {
            case self::MIGRATION_INSTALL:
                $result = $migration->up();
                break;
            case self::MIGRATION_UNINSTALL:
                $result = $migration->down();
                break;
            case self::MIGRATION_UPGRADE:
                $result = $migration->to($this->getOldAttribute('version'), $this->getAttribute('version'));
                break;
            default:
                throw new InvalidParamException("Migration type does not support '{$type}'.");
        }
        if ($result === false) {
            $this->addError('migration', '模块迁移脚本执行失败');
            return false;
        }
        return true;
    }

    /**
     * 是否已安装的模块
     * @return bool
     */
    public function getIsInstalled()
    {
        return !$this->getIsNewRecord();
    }

    /**
     * 安装模块
     * @param bool $runValidation
     * @return bool
     */
    public function install($runValidation = true)
    {
        return $this->save($runValidation);
    }

    /**
     * 卸载模块
     * @return false|int
     */
    public function uninstall()
    {
        return $this->delete();
    }

    /**
     * 根据模块的存放路径判断模块的类型
     */
    public function checkType($attribute, $params)
    {
        // 核心模块的优先级最高
        if (file_exists(Yii::getAlias(WechatModule::CORE_MODULE_PATH . '/' . $this->id . '/wechat.yml'))) {
            $type = self::TYPE_CORE;
        } else {
            $type = self::TYPE_ADDON;
        }
        if ($this->$attribute != $type) {
            return $this->addError($attribute, '模块类型匹配错误');
        }
    }

    /**
     * 模块数据列表缓存
     * 该数据只会返回数组形态模块数据,用于频繁操作(提高效率)的逻辑处理部分
     * @return array|mixed|\yii\db\ActiveRecord[]
     */
    public static function models()
    {
        $cache = Yii::$app->cache;
        if (($modules = $cache->get(self::CACHE_MODULES_DATA)) === false) {
            $modules = static::find()->indexBy('id')->asArray()->all();
            $cache->set(self::CACHE_MODULES_DATA, $modules, null, new TagDependency([
                'tags' => [self::CACHE_MODULES_DATA_DEPENDENCY_TAG]
            ]));
        }
        return $modules;
    }
}

controllers/ModuleController.php
<?php

namespace callmez\wechat\controllers;

use Yii;
use yii\data\ArrayDataProvider;
use yii\web\NotFoundHttpException;
use callmez\wechat\models\Module;
use callmez\wechat\helpers\ModuleHelper;
use callmez\wechat\components\AdminController;

/**
 * 扩展模块管理
 */
class ModuleController extends AdminController
{
    /**
     * 显示所有可用的扩展模块
     * @return mixed
     */
    public function actionIndex()
    {
        $models = $this->findInstalledModules();
        $dataProvider = new ArrayDataProvider([
            'allModels' => array_merge(ModuleHelper::findAvailableModules(), $models),
            // TODO 多model排序字段相同的话,会报错 @see https://github.com/yiisoft/yii2/issues/8348
//            'sort' => [
//                'attributes' => ['type'],
//                'defaultOrder' => [
//                    'type' => SORT_DESC
//                ]
//            ]
        ]);

        return $this->render('index', [
            'models' => $models,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * 安装模块
     * @param $id
     * @return array|bool|string
     * @throws NotFoundHttpException
     */
    public function actionInstall($id)
    {
        $model = $this->findAvailableModule($id);
        if (!$model->validate()) {
            return $this->message('模块的设置错误: ' . array_values($model->firstErrors)[0]);
        }
        if (!empty($_POST)) {
            if ($model->install(false)) {
                return $this->flash('模块安装成功!', 'success', ['index']);
            } elseif (!$model->hasErrors()) {
                return $this->flash('模块安装失败!', 'error');
            }
        }
        return $this->render('install', [
            'model' => $model
        ]);
    }

    /**
     * 卸载模块
     * @param $id
     * @return array|bool|string
     * @throws NotFoundHttpException
     */
    public function actionUninstall($id)
    {
        $model = $this->findInstalledModule($id);
        if (!empty($_POST)) {
            if ($model->uninstall()) {
                return $this->flash('模块卸载成功!', 'success', ['index']);
            } else {
                return $this->flash('模块卸载失败!', 'error');
            }
        }
        return $this->render('uninstall', [
            'model' => $model
        ]);
    }

    /**
     * 查找可用的扩展模块
     * @param $id
     * @return null
     * @throws NotFoundHttpException
     */
    public function findAvailableModule($id)
    {
        if (($model = ModuleHelper::findAvailableModuleById($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * 查找已安装的模块
     * @param $id
     * @return null|static
     * @throws NotFoundHttpException
     */
    public function findInstalledModule($id)
    {
        if (($model = Module::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
    
    /**
     * 查找已安装的模块
     * @return array|\yii\db\ActiveRecord[]
     */
    public function findInstalledModules()
    {
        return Module::find()->indexBy('id')->all();
    }
}

views/module/_form.php
<?php

use yii\helpers\Html;
use callmez\wechat\widgets\ActiveForm;

$wechat = Yii::$app->getModule('wechat');
?>

<div class="addon-module-form">
    <?php $form = ActiveForm::begin([
        'layout' => 'horizontal'
    ]); ?>

    <?= $form->errorSummary($model) ?>

    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'disabled' => true]) ?>

    <?= $form->field($model, 'id')->textInput(['maxlength' => true, 'disabled' => true]) ?>

    <?= $form->field($model, 'category')->dropDownList($wechat->getCategories(), ['disabled' => true]) ?>

    <?= $form->field($model, 'version')->textInput(['maxlength' => true, 'disabled' => true]) ?>

    <?= $form->field($model, 'ability')->textarea(['maxlength' => true, 'disabled' => true]) ?>

    <?= $form->field($model, 'description')->textarea(['rows' => 6, 'disabled' => true]) ?>

    <?= $form->field($model, 'author')->textInput(['maxlength' => true, 'disabled' => true]) ?>

    <?= $form->field($model, 'site')->textInput(['maxlength' => true, 'disabled' => true]) ?>

    <div class="form-group">
        <div class="col-sm-offset-3 col-sm-6">
            <?= Html::submitButton($model->isInstalled ? '卸载模块' : '安装模块', ['class' => $model->isInstalled ? 'btn btn-block btn-danger' : 'btn btn-block btn-success']) ?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/module/index.php
<?php

use yii\helpers\Html;
use callmez\wechat\models\Module;
use callmez\wechat\widgets\GridView;
use callmez\wechat\widgets\PagePanel;

$this->title = '模块管理';
$this->params['breadcrumbs'][] = $this->title;
$wechat = Yii::$app->getModule('wechat');
if ($wechat->canCreateModule()) {
    $createModule = Html::a('我要设计新模块', ["/{$wechat->giiModuleName}/{$wechat->giiGeneratorName}"], ['class' => 'pull-right']);
} else {
    $createModule = Html::a('想设计新模块?', 'https://github.com/callmez/yii2-wechat/blob/master/docs/addon-module.md', ['class' => 'pull-right']);
}
?>
<?php PagePanel::begin([
    'rightHtml' => $createModule,
    'options' => ['class' => 'addon-module-index'
]]) ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            'name',
            'id',
            [
                'attribute' => 'type',
                'format' => 'html',
                'value' => function ($model) use ($models) {
                    return Html::tag('span', Module::$types[$model->type], [
                        'class' => 'label label-' . ($model->type == Module::TYPE_CORE ? 'danger' : 'info')
                    ]);
                },
            ],
            'version',
            [
                'attribute' => 'author',
                'format' => 'html',
                'value' => function ($model) {
                    $author = $model->author ?: '匿名';
                    return $model->site ? Html::a($author, $model->site) : Html::encode($author) ;
                },
                'options' => [
                    'width' => 80
                ]
            ],
            'ability',
            [
                'header' => '安装状态',
                'format' => 'html',
                'value' => function ($model) use ($models) {
                    $installed = $model->getIsInstalled();
                    return Html::tag('span', $installed ? '已安装' : '未安装', [
                        'class' => 'label label-' . ($installed ? 'warning' : 'success')
                    ]);
                },
            ],
            'created_at:datetime',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{install}',
                'buttons' => [
                    'install' => function ($url, $model, $key) use ($models) {
                        if ($model->getIsInstalled()) {
                            return Html::a('卸载模块', ['uninstall', 'id' => $model->id], ['data-confirm' => '确定要卸载此模块?']);
                        } else {
                            return Html::a('安装模块', ['install', 'id' => $model->id]);
                        }
                    }
                ]
            ],
        ],
    ]); ?>
<?php PagePanel::end() ?>

views/module/install.php
<?php

use yii\helpers\Html;
use callmez\wechat\widgets\PagePanel;


$this->title = '安装 ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => '模块管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php PagePanel::begin(['options' => ['class' => 'addon-module-install']]) ?>
        <?= $this->render('_form', [
            'model' => $model,
        ]) ?>
<?php PagePanel::end() ?>

views/module/uninstall.php
<?php

use yii\helpers\Html;
use callmez\wechat\widgets\PagePanel;

$this->title = '卸载 ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => '模块管理', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<?php PagePanel::begin(['options' => ['class' => 'addon-module-uninstall']]) ?>
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
<?php PagePanel::end() ?>